# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model/agent_config_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgentConfigWindow(object):
    def setupUi(self, AgentConfigWindow):
        AgentConfigWindow.setObjectName("AgentConfigWindow")
        AgentConfigWindow.resize(817, 699)
        self.centralwidget = QtWidgets.QWidget(AgentConfigWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 771, 631))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_confirm = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.verticalLayout_2.addWidget(self.pushButton_confirm)
        self.pushButton_reset = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout_2.addWidget(self.pushButton_reset)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        AgentConfigWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AgentConfigWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        AgentConfigWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AgentConfigWindow)
        self.statusbar.setObjectName("statusbar")
        AgentConfigWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(AgentConfigWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave = QtWidgets.QAction(AgentConfigWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(AgentConfigWindow)
        QtCore.QMetaObject.connectSlotsByName(AgentConfigWindow)

    def retranslateUi(self, AgentConfigWindow):
        _translate = QtCore.QCoreApplication.translate
        AgentConfigWindow.setWindowTitle(_translate("AgentConfigWindow", "MainWindow"))
        self.pushButton_confirm.setText(_translate("AgentConfigWindow", "Confim"))
        self.pushButton_reset.setText(_translate("AgentConfigWindow", "Reset"))
        self.menuFile.setTitle(_translate("AgentConfigWindow", "File"))
        self.actionQuit.setText(_translate("AgentConfigWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("AgentConfigWindow", "Esc"))
        self.actionSave.setText(_translate("AgentConfigWindow", "Save"))
        self.actionSave.setShortcut(_translate("AgentConfigWindow", "Ctrl+S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgentConfigWindow = QtWidgets.QMainWindow()
    ui = Ui_AgentConfigWindow()
    ui.setupUi(AgentConfigWindow)
    AgentConfigWindow.show()
    sys.exit(app.exec_())
