# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model/main_menu_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(711, 711)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outerframe = QtWidgets.QFrame(self.centralwidget)
        self.outerframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outerframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outerframe.setObjectName("outerframe")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.outerframe)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.outerframe)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushbtnfram1 = QtWidgets.QFrame(self.frame)
        self.pushbtnfram1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pushbtnfram1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pushbtnfram1.setObjectName("pushbtnfram1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pushbtnfram1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushbtn_simconfig = QtWidgets.QPushButton(self.pushbtnfram1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushbtn_simconfig.setFont(font)
        self.pushbtn_simconfig.setObjectName("pushbtn_simconfig")
        self.verticalLayout_3.addWidget(self.pushbtn_simconfig)
        self.pushbtn_jetsonconfig = QtWidgets.QPushButton(self.pushbtnfram1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushbtn_jetsonconfig.setFont(font)
        self.pushbtn_jetsonconfig.setObjectName("pushbtn_jetsonconfig")
        self.verticalLayout_3.addWidget(self.pushbtn_jetsonconfig)
        self.gridLayout_4.addWidget(self.pushbtnfram1, 1, 0, 1, 1)
        self.welcomeframe = QtWidgets.QFrame(self.frame)
        self.welcomeframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.welcomeframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.welcomeframe.setObjectName("welcomeframe")
        self.label = QtWidgets.QLabel(self.welcomeframe)
        self.label.setGeometry(QtCore.QRect(160, 110, 311, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.welcomeframe, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.outerframe)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 711, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushbtn_simconfig.setText(_translate("MainWindow", "ROAR Simulation Configuration"))
        self.pushbtn_jetsonconfig.setText(_translate("MainWindow", "ROAR Jetson Configuration"))
        self.label.setText(_translate("MainWindow", "   Welcom to ROAR GUI"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Esc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
