# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model/simulation_config_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimulationConfigWindow(object):
    def setupUi(self, SimulationConfigWindow):
        SimulationConfigWindow.setObjectName("SimulationConfigWindow")
        SimulationConfigWindow.resize(804, 623)
        self.centralwidget = QtWidgets.QWidget(SimulationConfigWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 681, 531))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_confirm = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.verticalLayout_2.addWidget(self.pushButton_confirm)
        self.pusbButton_reset = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pusbButton_reset.setObjectName("pusbButton_reset")
        self.verticalLayout_2.addWidget(self.pusbButton_reset)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        SimulationConfigWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SimulationConfigWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        SimulationConfigWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SimulationConfigWindow)
        self.statusbar.setObjectName("statusbar")
        SimulationConfigWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(SimulationConfigWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave = QtWidgets.QAction(SimulationConfigWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(SimulationConfigWindow)
        QtCore.QMetaObject.connectSlotsByName(SimulationConfigWindow)

    def retranslateUi(self, SimulationConfigWindow):
        _translate = QtCore.QCoreApplication.translate
        SimulationConfigWindow.setWindowTitle(_translate("SimulationConfigWindow", "MainWindow"))
        self.pushButton_confirm.setText(_translate("SimulationConfigWindow", "confirm"))
        self.pusbButton_reset.setText(_translate("SimulationConfigWindow", "reset"))
        self.menuFile.setTitle(_translate("SimulationConfigWindow", "File"))
        self.actionQuit.setText(_translate("SimulationConfigWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("SimulationConfigWindow", "Esc"))
        self.actionSave.setText(_translate("SimulationConfigWindow", "Save"))
        self.actionSave.setShortcut(_translate("SimulationConfigWindow", "Ctrl+S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SimulationConfigWindow = QtWidgets.QMainWindow()
    ui = Ui_SimulationConfigWindow()
    ui.setupUi(SimulationConfigWindow)
    SimulationConfigWindow.show()
    sys.exit(app.exec_())
